### ISSUE TITLE
Serverless CLI: Image Optimization Lambda seems to try using inexistent __dirname,"./threadChild.js"

### ISSUE THREAD

**Issue by celso-alexandre** [sst/open-next#373]
open-next version: 2.3.6
System: Linux Mint Linux 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Deploy:
I'm using serverless CLI. I may be missing something, maybe SST would've add the missing file before zipping it
```yml
before:package:createDeploymentArtifacts:
  - yarn open-next build --minify
  - mkdir -p ./.open-next/zips
  - cd .open-next/server-function && zip -r ../zips/server-function.zip .
  - cd .open-next/image-optimization-function && zip -r ../zips/image-optimization-function.zip .
  - cd .open-next/revalidation-function && zip -r ../zips/revalidation-function.zip .
  - cd .open-next/warmer-function && zip -r ../zips/warmer-function.zip .
```
My full serverless.yml: https://github.com/sst/open-next/issues/32#issuecomment-1973330303

Description:
It seems that the generated "image-optimization" lambda is trying to import the file __dirname,"./threadChild.js", which was not generated

This is the cloudwatch log error I'm getting:
```
ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '/var/task/threadChild.js'",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [],
    "stack": [
        "Error: Cannot find module '/var/task/threadChild.js'",
        "    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)",
        "    at Module._load (node:internal/modules/cjs/loader:985:27)",
        "    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)",
        "    at MessagePort.<anonymous> (node:internal/main/worker_thread:186:26)",
        "    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:826:20)",
        "    at exports.emitMessage (node:internal/per_context/messageport:23:28)"
    ]
}
```

The following were produced by `yarn open-next build`
open-next version: 2.3.6
![image](https://github.com/sst/open-next/assets/37484505/c2776da5-25a7-4f4d-815c-08af96952432)
![image](https://github.com/sst/open-next/assets/37484505/57e5b949-01c6-49d2-87aa-64da3db302d0)

**Comment by conico974** [comment]
2.3.6 is broken with image opt, you can downgrade to 2.3.5 or set `SHARP_VERSION="0.32.6"` env variable before running `open-next build`. 
Someone has reported an issue with 0.32.6 as well but i haven't had time to reproduce the issue yet and it seems that most people are managing to make it work with 0.32.6.
That's the PR for 2.3.6, there is more info here : https://github.com/sst/open-next/pull/361

**Comment by celso-alexandre** [comment]
Thanks for replying, and I must say I'm very much amused by this piece of software, and I've learned a lot with it.
I've updated the description with my current serverless.yml definition.

I should add that after setting the variable as building `SHARP_VERSION="0.32.6" yarn open-next build --minify`, the lambda function "image-optimization-function" still produces an import of the inexistent file "./threadChild.js".
I will soon report back if the error persists

**Comment by khuezy** [comment]
What next version are you currently on? `sharp` said [https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.28](https://github.com/vercel/next.js/releases/tag/v14.1.1-canary.28) fixed some things regards to it; can you try installing the latest 14.1.1 canary to see if it does indeed fix the problem?

**Comment by celso-alexandre** [comment]
Thanks for helping. I can confirm after a couple tests that this exact line is not called anymore by changing the sharp version to 0.32.6. Many thanks
